# Market Parameters
SYMBOL = "ArthaVedh"
DESIRED_SPREAD = 2.0
BASE_PRICE_MIN = 100
BASE_PRICE_MAX = 200
SHOCK_RANGE_MIN = -25
SHOCK_RANGE_MAX = 25
ASK_PRICE_MIN_SPREAD = 0.01
ASK_PRICE_MAX_SPREAD = 5

# Trading Parameters
INITIAL_CAPITAL = 100000
TRANSACTION_COST_PERCENTAGE = 0.02
SLIPPAGE_RANGE_MIN = -2.0
SLIPPAGE_RANGE_MAX = 2.0
MEAN_REVERSION_THRESHOLD = 5.0
MAX_PROFIT_LIMIT = 3000
MAX_LOSS_LIMIT = -3000

# Technical Indicators
PRICE_HISTORY_LENGTH = 50
MOVING_AVERAGE_PERIOD = 5

# Market Events
MARKET_DOWNTURN_PROBABILITY = 0.2
MARKET_DOWNTURN_TRENDS = [-0.2, -0.25]
MARKET_TRENDS = [0, 0.05, -0.05]

# Time Parameters
HOLDING_PERIOD = 2  # seconds
TRADING_INTERVAL = 0.01  # seconds

# Logging Configuration
LOG_FILE = "high_frequency_trading.log"
LOG_FORMAT = '%(asctime)s - %(levelname)s - %(message)s'
LOG_LEVEL = "INFO"